routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('main.index');
//})->name('main.page');

Route::get('/', [\App\Http\Controllers\Main\MainController::class, 'index'])->name('main.page');
Route::get('/category/{id}',[\App\Http\Controllers\Main\MainController::class, 'category_filter'])->name('category.filter');
Route::get('/subcategory/{id}',[\App\Http\Controllers\Main\MainController::class, 'subcategory_filter'])->name('subcategory.filter');
Route::get('/price/{prc}', [\App\Http\Controllers\Main\MainController::class, 'price_filter'])->name('price.filter');
Route::get('/size/{sz}', [\App\Http\Controllers\Main\MainController::class, 'size_filter'])->name('size.filter');
Route::get('/type/{type}', [\App\Http\Controllers\Main\MainController::class, 'type_filter'])->name('type.filter');


Route::middleware(['middleware'=>'back'])->group(function (){
    Auth::routes();
});





//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'dashboard', 'middleware'=>['auth','admin','back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'adminpanel'])->name('adminpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit'])->name('dashboard.setting');
    Route::put('/update/{user}',[\App\Http\Controllers\HomeController::class, 'update'])->name('dashboard.update');
    Route::resource('/role', \App\Http\Controllers\Admin\RoleController::class);
    Route::get('/notifications', [\App\Http\Controllers\User\PetitionController::class, 'notifications'])->name('dashboard.notifications');
    Route::get('/notification/{petition}', [\App\Http\Controllers\User\PetitionController::class, 'notificationshow'])->name('dashboard.notificationshow');
    Route::get('/notification/accept/{petition}',[\App\Http\Controllers\User\PetitionController::class, 'notification_accept'])->name('dashboard.notification_accept');
    Route::post('/notification/cancel/{petition}',[\App\Http\Controllers\User\PetitionController::class, 'notification_cancel'])->name('dashboard.notification_cancel');
    Route::resource('/category', \App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('/subcategory', \App\Http\Controllers\Admin\SubcategoryController::class);
    Route::get('/architectors', [\App\Http\Controllers\Admin\MembersController::class, 'architectors'])->name('dashboard.architectors');
    Route::get('/users', [\App\Http\Controllers\Admin\MembersController::class, 'users'])->name('dashboard.users');
    Route::get('/receive', [\App\Http\Controllers\Architector\ProductController::class, 'recieve'])->name('product.recieve');
    Route::get('/receive/{product}', [\App\Http\Controllers\Architector\ProductController::class, 'show_receive'])->name('product.show_receive');
    Route::post('/product/block', [\App\Http\Controllers\Architector\ProductController::class, 'accept_block'])->name('product.block');
    Route::get('/product/accepts', [\App\Http\Controllers\Architector\ProductController::class, 'accept_models'])->name('product.accept');
    Route::get('/product/cancels', [\App\Http\Controllers\Architector\ProductController::class, 'cancel_models'])->name('product.cancel');
    Route::get('/product/press_accept/{product}', [\App\Http\Controllers\Architector\ProductController::class, 'press_accept'])->name('products.press_accept');
    Route::post('/product/cancel/{product}', [\App\Http\Controllers\Architector\ProductController::class, 'reason'])->name('product.reason');
    Route::post('/spam/architector/{architector}', [\App\Http\Controllers\Architector\SpamController::class, 'architec_spam'])->name('architec.spam');
    Route::get('/nospam/architector/{architector}', [\App\Http\Controllers\Architector\SpamController::class, 'architec_nospam'])->name('architec.nospam');
    Route::post('/spam/user/{user}', [\App\Http\Controllers\Architector\SpamController::class, 'user_spam'])->name('user.spam');
    Route::get('/nospam/user/{user}', [\App\Http\Controllers\Architector\SpamController::class, 'user_nospam'])->name('user.nospam');
    Route::get('/messenger', [\App\Http\Controllers\Admin\AmessengerController::class, 'create'])->name('members.messenger');
    Route::get('/chat/{member}', [\App\Http\Controllers\Admin\AmessengerController::class, 'chat_member'])->name('members.chat');
    Route::post('/messege/text/{account}', [\App\Http\Controllers\Admin\AmessengerController::class, 'admin_message_text'])->name('admin_text_message');
    Route::post('/search', [\App\Http\Controllers\Admin\AmessengerController::class, 'search'])->name('members.search');
    Route::get('/contact', [\App\Http\Controllers\Main\ContactController::class, 'recieve_contact'])->name('recieve.contact');
});

Route::group(['prefix'=>'architector', 'middleware'=>['auth','architector','back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'archtecpanel'])->name('architecpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit_arch'])->name('architec.setting');
    Route::put('/update/{user}', [\App\Http\Controllers\HomeController::class, 'update_arch'])->name('architec.update');
    Route::resource('/product', \App\Http\Controllers\Architector\ProductController::class);
    Route::post('/select/category', [\App\Http\Controllers\Architector\ProductController::class, 'select_category'])->name('architec.category');
    Route::post('/select/subcategory', [\App\Http\Controllers\Architector\ProductController::class,'select_subcategory'])->name('architec.subcategory');
    Route::get('/chat', [\App\Http\Controllers\Admin\AmessengerController::class, 'chat_with_admin'])->name('admin.chat');
    Route::post('/messege/text', [\App\Http\Controllers\Admin\AmessengerController::class, 'architec_text_message'])->name('architec_text_message');
});

Route::group(['prefix'=>'user', 'middleware'=>['auth','user','back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'userpanel'])->name('userpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit_user'])->name('user.setting');
    Route::put('/update/{user}', [\App\Http\Controllers\HomeController::class, 'update_user'])->name('user.update');
    Route::resource('/petition', \App\Http\Controllers\User\PetitionController::class);
    Route::get('/chat', [\App\Http\Controllers\Admin\AmessengerController::class, 'user_chat_with_admin'])->name('user.chat');
    Route::post('/messege/text', [\App\Http\Controllers\Admin\AmessengerController::class, 'user_text_message'])->name('user_text_message');
});

Route::get('/contact', [\App\Http\Controllers\Main\ContactController::class, 'contact_page'])->name('main.contact');
Route::post('/send', [\App\Http\Controllers\Main\ContactController::class, 'store'])->name('contact.store');
Route::get('/product/detail/{product_accept}', [\App\Http\Controllers\Architector\ProductController::class, 'product_detail'])->name('product_detail');

app/Models/Petition.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Petition extends Model
{
    use HasFactory;

    public function user_name()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','lname', 'email', 'password','role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/User/PetitionController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Petition;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

class PetitionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $petitions = Petition::where('user_id','=',Auth::user()->id)->orderBy('id','desc')->get();
        return view('user.petitions.view', compact('petitions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.petitions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'petition_text'=>'required'
        ]);
        $petition_text = $request->input('petition_text');
        $portfolio = $request->input('portfolio_link');
        $petition = new Petition();
        $petition->user_id = Auth::user()->id;
        $petition->status = 0;
        $petition->petition_text = $petition_text;
        $petition->portfolio_link = $portfolio;
        $petition->save();
        Alert::success('Success Title', 'Petition sent successfully');
        return redirect()->route('petition.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(Petition $petition)
    {
        return view('user.petitions.edit', compact('petition'));
    }

    /**
     * @param Request $request
     * @param Petition $petition
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Petition $petition)
    {
        $petition_text = $request->input('petition_text');
        $portfolio = $request->input('portfolio_link');

        $petition->petition_text = $petition_text;
        $petition->portfolio_link = $portfolio;
        $petition->update();
        Alert::success('Success Title', 'Petition updated successfully');
        return redirect()->route('petition.index');
    }

    /**
     * @param Petition $petition
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Petition $petition)
    {
        $petition->delete();
        return redirect()->route('petition.index');
    }

    public function notifications()
    {
        $petitions = Petition::where('status','=',0)->orderBy('id','desc')->get();
        return view('admin.petitions.index', compact('petitions'));
    }

    public function notificationshow(Petition $petition)
    {
        return view('admin.petitions.show', compact('petition'));
    }

    public function notification_accept(Petition $petition)
    {

        Petition::where('id','=',$petition->id)->update([
            'status'=>1
        ]);
        User::where('id','=',$petition->user_id)->update([
            'role'=>2
        ]);

        return redirect()->route('dashboard.notifications');
    }

    public function notification_cancel(Request $request, Petition $petition)
    {
        $result = $request->input('result_description');
        Petition::where('id','=', $petition->id)
            ->update([
                'status'=>2,
                'result_description'=>$result
            ]);
        return redirect()->route('dashboard.notifications');
    }
}

resources/views/user/petitions/create.blade.php
@extends('user.layouts.master')
@section('title','Create petition')
@section('content')
{{--    <div class="col-md-12">--}}
{{--        <div class="card mb-4">--}}
{{--            <form action="{{route('petition.store')}}" method="POST">--}}
{{--                @csrf--}}
{{--                @method('POST')--}}
{{--                <h5 class="card-header">You can send petition to Administrator for add to role Architector</h5>--}}
{{--                <div class="card-body">--}}
{{--                    <div>--}}
{{--                        <label for="exampleFormControlTextarea1" class="form-label">Petition text</label>--}}
{{--                        <textarea name="petition_text" class="form-control @error('petition_text') is-invalid @enderror" id="exampleFormControlTextarea1" rows="3"></textarea>--}}
{{--                        @error('petition_text')--}}
{{--                            <span class="invalid-feedback" role="alert">--}}
{{--                                <strong>{{ $message }}</strong>--}}
{{--                            </span>--}}
{{--                        @enderror--}}
{{--                    </div>--}}
{{--                    <br>--}}
{{--                    <div>--}}
{{--                        <label for="exampleFormControlTextarea1" class="form-label">Your portfolio link</label>--}}
{{--                        <input placeholder="https://" type="text" class="form-control" name="portfolio_link">--}}
{{--                    </div>--}}
{{--                    <br>--}}
{{--                    <div>--}}
{{--                        <input type="submit" value="send" class="btn btn-success">--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </form>--}}
{{--        </div>--}}
{{--    </div>--}}
<div class="select2-drpdwn">
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-3">
                <form action="{{route('petition.store')}}" method="post">
                    @csrf
                    <div class="card-header">
                        <h5 class="card-title">Create petition</h5>
                    </div>
                    <div class="card-body o-hidden">
                        <div class="mb-2">
                            <div class="col-form-label">Petition text</div>
                            <textarea name="petition_text" class="form-control @error('petition_text') is-invalid @enderror" id="exampleFormControlTextarea1" rows="3"></textarea>
                            @error('petition_text')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                        <div class="mb-2">
                            <div class="col-form-label">Portfolio link</div>
                            <input placeholder="https://..." name="portfolio_link" class="form-control @error('portfolio_link') is-invalid @enderror" id="exampleFormControlTextarea1"/>
                            @error('portfolio_link')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                        <div class="mb-2">
                            <input type="submit" class="btn btn-primary" value="send petition">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/petitions/edit.blade.php
@extends('user.layouts.master')
@section('title','Update petition')
@section('content')
{{--    <div class="col-md-12">--}}
{{--        <div class="card mb-4">--}}
{{--            <form action="{{route('petition.update',$petition)}}" method="POST">--}}
{{--                @csrf--}}
{{--                @method('PUT')--}}
{{--                <h5 class="card-header">You can send petition to Administrator for add to role Architector</h5>--}}
{{--                <div class="card-body">--}}
{{--                    <div>--}}
{{--                        <label for="exampleFormControlTextarea1" class="form-label">Petition text</label>--}}
{{--                        <textarea name="petition_text" class="form-control @error('petition_text') is-invalid @enderror" id="exampleFormControlTextarea1" rows="3">{{$petition->petition_text}}</textarea>--}}
{{--                        @error('petition_text')--}}
{{--                        <span class="invalid-feedback" role="alert">--}}
{{--                                <strong>{{ $message }}</strong>--}}
{{--                            </span>--}}
{{--                        @enderror--}}
{{--                    </div>--}}
{{--                    <br>--}}
{{--                    <div>--}}
{{--                        <label for="exampleFormControlTextarea1" class="form-label">Your portfolio link</label>--}}
{{--                        <input value="{{$petition->portfolio_link}}" placeholder="https://" type="text" class="form-control" name="portfolio_link">--}}
{{--                    </div>--}}
{{--                    <br>--}}
{{--                    <div>--}}
{{--                        <input type="submit" value="update" class="btn btn-success">--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </form>--}}
{{--        </div>--}}
{{--    </div>--}}

<div class="select2-drpdwn">
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-3">
                <form action="{{route('petition.update', $petition)}}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="card-header">
                        <h5 class="card-title">Create petition</h5>
                    </div>
                    <div class="card-body o-hidden">
                        <div class="mb-2">
                            <div class="col-form-label">Petition text</div>
                            <textarea name="petition_text" class="form-control @error('petition_text') is-invalid @enderror" id="exampleFormControlTextarea1" rows="3">{{$petition->petition_text}}</textarea>
                            @error('petition_text')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                        <div class="mb-2">
                            <div class="col-form-label">Portfolio link</div>
                            <input value="{{$petition->portfolio_link}}" placeholder="https://..." name="portfolio_link" class="form-control @error('portfolio_link') is-invalid @enderror" id="exampleFormControlTextarea1"/>
                            @error('portfolio_link')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                        <div class="mb-2">
                            <input type="submit" class="btn btn-primary" value="update petition">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/petitions/view.blade.php
@extends('user.layouts.master')
@section('title','View your petitions')
@section('content')
{{--    <div class="card">--}}
{{--        <h5 class="card-header">Dark Table head</h5>--}}
{{--        <div class="table-responsive text-nowrap">--}}
{{--            <table class="table">--}}
{{--                <thead class="table-dark">--}}
{{--                <tr>--}}
{{--                    <th>#</th>--}}
{{--                    <th>Status</th>--}}
{{--                    <th>Petition text</th>--}}
{{--                    <th>Portfolio link</th>--}}
{{--                    <th>Result</th>--}}
{{--                    <th>Actions</th>--}}
{{--                </tr>--}}
{{--                </thead>--}}
{{--                <tbody class="table-border-bottom-0">--}}
{{--                @foreach($petitions as $key => $petition)--}}
{{--                <tr>--}}
{{--                    <td><i class="fab fa-angular fa-lg text-danger me-3"></i>--}}
{{--                        <strong> {{$key+1}} </strong>--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        @if($petition->status == 0)--}}
{{--                            <span class="badge bg-label-warning me-1">Checking</span>--}}
{{--                        @elseif($petition->status == 1)--}}
{{--                            <span class="badge bg-label-success me-1">Accept</span>--}}
{{--                        @elseif($petition->status == 2)--}}
{{--                            <span class="badge bg-label-danger me-1">Cancel</span>--}}
{{--                        @endif--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        {{substr($petition->petition_text, 0,30)}}..--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        {{substr($petition->portfolio_link, 0, 30)}}..--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                            <div class="">--}}
{{--                                <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#basicModal">--}}
{{--                                    result--}}
{{--                                </button>--}}

{{--                                <!-- Modal -->--}}
{{--                                <div class="modal fade" id="basicModal" tabindex="-1" aria-hidden="true">--}}
{{--                                    <div class="modal-dialog" role="document">--}}
{{--                                        <div class="modal-content">--}}
{{--                                            <div class="modal-header">--}}
{{--                                                <h5 class="modal-title" id="exampleModalLabel1">Message from Administrator</h5>--}}
{{--                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>--}}
{{--                                            </div>--}}
{{--                                            <div class="modal-body">--}}
{{--                                                <div class="row">--}}
{{--                                                    <div class="col mb-3">--}}
{{--                                                        <p class="">{{$petition->result_description}}</p>--}}
{{--                                                    </div>--}}
{{--                                                </div>--}}

{{--                                            </div>--}}
{{--                                            <div class="modal-footer">--}}
{{--                                                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">--}}
{{--                                                    Close--}}
{{--                                                </button>--}}
{{--                                            </div>--}}
{{--                                        </div>--}}
{{--                                    </div>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                    </td>--}}
{{--                    <td class="d-flex">--}}
{{--                        <a href="{{route('petition.edit', $petition)}}" class="btn btn-primary">Edit</a>--}}
{{--                        &nbsp;<form action="{{route('petition.destroy', $petition)}}" method="post">--}}
{{--                            @csrf--}}
{{--                            @method('DELETE')--}}
{{--                            <button type="submit" class="btn btn-danger show_confirm">Delete</button>--}}
{{--                        </form>--}}
{{--                    </td>--}}
{{--                </tr>--}}
{{--                @endforeach--}}
{{--                </tbody>--}}
{{--            </table>--}}
{{--        </div>--}}
{{--    </div>--}}

<br><br>
<div class="col-sm-12">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5>All categories</h5>
            <a href="{{route('petition.create')}}" class="btn btn-primary">create petition</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="display" id="basic-1">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Status</th>
                        <th>Petition text</th>
                        <th>Portfolio link</th>
                        <th>Result</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($petitions as $key=>$petition)
                        <tr>
                            <td><i class="fab fa-angular fa-lg text-danger me-3"></i>
                                <strong> {{$key+1}} </strong>
                            </td>
                            <td>
                                @if($petition->status == 0)
                                    <span class="badge badge-warning">Checking</span>
                                @elseif($petition->status == 1)
                                    <span class="badge badge-success">Accept</span>
                                @elseif($petition->status == 2)
                                    <span class="badge badge-danger">Cancel</span>
                                @endif
                            </td>
                            <td>
                                {{substr($petition->petition_text, 0,30)}}..
                            </td>
                            <td>
                                {{substr($petition->portfolio_link, 0, 30)}}..
                            </td>
                            <td>
                                    <div class="">
                                        <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#basicModal">
                                            result
                                        </button>

                                        <!-- Modal -->
                                        <div class="modal fade" id="basicModal" tabindex="-1" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel1">Message from Administrator</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="row">
                                                            <div class="col mb-3">
                                                                <p class="">{{$petition->result_description}}</p>
                                                            </div>
                                                        </div>

                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                                            Close
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </td>
                            <td class="d-flex">
                                <a href="{{route('petition.edit', $petition)}}" class="btn btn-primary">Edit</a>
                                &nbsp;<form action="{{route('petition.destroy', $petition)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger show_confirm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@endsection
@push('script')
    <script type="text/javascript">

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Do you want delete petition?`,
                // text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>

@endpush