routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('main.index');
//})->name('main.page');

Route::get('/', [\App\Http\Controllers\Main\MainController::class, 'index'])->name('main.page');
Route::get('/category/{id}',[\App\Http\Controllers\Main\MainController::class, 'category_filter'])->name('category.filter');
Route::get('/subcategory/{id}',[\App\Http\Controllers\Main\MainController::class, 'subcategory_filter'])->name('subcategory.filter');
Route::get('/price/{prc}', [\App\Http\Controllers\Main\MainController::class, 'price_filter'])->name('price.filter');
Route::get('/size/{sz}', [\App\Http\Controllers\Main\MainController::class, 'size_filter'])->name('size.filter');
Route::get('/type/{type}', [\App\Http\Controllers\Main\MainController::class, 'type_filter'])->name('type.filter');


Route::middleware(['middleware'=>'back'])->group(function (){
    Auth::routes();
});





//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'dashboard', 'middleware'=>['auth','admin','back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'adminpanel'])->name('adminpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit'])->name('dashboard.setting');
    Route::put('/update/{user}',[\App\Http\Controllers\HomeController::class, 'update'])->name('dashboard.update');
    Route::resource('/role', \App\Http\Controllers\Admin\RoleController::class);
    Route::get('/notifications', [\App\Http\Controllers\User\PetitionController::class, 'notifications'])->name('dashboard.notifications');
    Route::get('/notification/{petition}', [\App\Http\Controllers\User\PetitionController::class, 'notificationshow'])->name('dashboard.notificationshow');
    Route::get('/notification/accept/{petition}',[\App\Http\Controllers\User\PetitionController::class, 'notification_accept'])->name('dashboard.notification_accept');
    Route::post('/notification/cancel/{petition}',[\App\Http\Controllers\User\PetitionController::class, 'notification_cancel'])->name('dashboard.notification_cancel');
    Route::resource('/category', \App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('/subcategory', \App\Http\Controllers\Admin\SubcategoryController::class);
    Route::get('/architectors', [\App\Http\Controllers\Admin\MembersController::class, 'architectors'])->name('dashboard.architectors');
    Route::get('/users', [\App\Http\Controllers\Admin\MembersController::class, 'users'])->name('dashboard.users');
    Route::get('/receive', [\App\Http\Controllers\Architector\ProductController::class, 'recieve'])->name('product.recieve');
    Route::get('/receive/{product}', [\App\Http\Controllers\Architector\ProductController::class, 'show_receive'])->name('product.show_receive');
    Route::post('/product/block', [\App\Http\Controllers\Architector\ProductController::class, 'accept_block'])->name('product.block');
    Route::get('/product/accepts', [\App\Http\Controllers\Architector\ProductController::class, 'accept_models'])->name('product.accept');
    Route::get('/product/cancels', [\App\Http\Controllers\Architector\ProductController::class, 'cancel_models'])->name('product.cancel');
    Route::get('/product/press_accept/{product}', [\App\Http\Controllers\Architector\ProductController::class, 'press_accept'])->name('products.press_accept');
    Route::post('/product/cancel/{product}', [\App\Http\Controllers\Architector\ProductController::class, 'reason'])->name('product.reason');
    Route::post('/spam/architector/{architector}', [\App\Http\Controllers\Architector\SpamController::class, 'architec_spam'])->name('architec.spam');
    Route::get('/nospam/architector/{architector}', [\App\Http\Controllers\Architector\SpamController::class, 'architec_nospam'])->name('architec.nospam');
    Route::post('/spam/user/{user}', [\App\Http\Controllers\Architector\SpamController::class, 'user_spam'])->name('user.spam');
    Route::get('/nospam/user/{user}', [\App\Http\Controllers\Architector\SpamController::class, 'user_nospam'])->name('user.nospam');
    Route::get('/messenger', [\App\Http\Controllers\Admin\AmessengerController::class, 'create'])->name('members.messenger');
    Route::get('/chat/{member}', [\App\Http\Controllers\Admin\AmessengerController::class, 'chat_member'])->name('members.chat');
    Route::post('/messege/text/{account}', [\App\Http\Controllers\Admin\AmessengerController::class, 'admin_message_text'])->name('admin_text_message');
    Route::post('/search', [\App\Http\Controllers\Admin\AmessengerController::class, 'search'])->name('members.search');
    Route::get('/contact', [\App\Http\Controllers\Main\ContactController::class, 'recieve_contact'])->name('recieve.contact');
});

Route::group(['prefix'=>'architector', 'middleware'=>['auth','architector','back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'archtecpanel'])->name('architecpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit_arch'])->name('architec.setting');
    Route::put('/update/{user}', [\App\Http\Controllers\HomeController::class, 'update_arch'])->name('architec.update');
    Route::resource('/product', \App\Http\Controllers\Architector\ProductController::class);
    Route::post('/select/category', [\App\Http\Controllers\Architector\ProductController::class, 'select_category'])->name('architec.category');
    Route::post('/select/subcategory', [\App\Http\Controllers\Architector\ProductController::class,'select_subcategory'])->name('architec.subcategory');
    Route::get('/chat', [\App\Http\Controllers\Admin\AmessengerController::class, 'chat_with_admin'])->name('admin.chat');
    Route::post('/messege/text', [\App\Http\Controllers\Admin\AmessengerController::class, 'architec_text_message'])->name('architec_text_message');
});

Route::group(['prefix'=>'user', 'middleware'=>['auth','user','back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'userpanel'])->name('userpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit_user'])->name('user.setting');
    Route::put('/update/{user}', [\App\Http\Controllers\HomeController::class, 'update_user'])->name('user.update');
    Route::resource('/petition', \App\Http\Controllers\User\PetitionController::class);
    Route::get('/chat', [\App\Http\Controllers\Admin\AmessengerController::class, 'user_chat_with_admin'])->name('user.chat');
    Route::post('/messege/text', [\App\Http\Controllers\Admin\AmessengerController::class, 'user_text_message'])->name('user_text_message');
});

Route::get('/contact', [\App\Http\Controllers\Main\ContactController::class, 'contact_page'])->name('main.contact');
Route::post('/send', [\App\Http\Controllers\Main\ContactController::class, 'store'])->name('contact.store');
Route::get('/product/detail/{product_accept}', [\App\Http\Controllers\Architector\ProductController::class, 'product_detail'])->name('product_detail');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Subcategory;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.view', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
           'category_name'=>'required'
        ]);

        $category_name = $request->input('category_name');
        $category = new Category();
        $category->category_name = $category_name;
        $category->save();
        Alert::success('Success Title', 'Category added successfully');
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'category_name'=>'required'
        ]);
        $category->category_name = $request->input('category_name');
        $category->update();
        Alert::success('Success Title', 'Category updated successfully');
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function destroy(Category $category)
    {
        Subcategory::where('category_id','=',$category->id)->delete();
        $category->delete();
        return redirect()->route('category.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')
@section('title', 'Add category')
@section('content')
    <div class="select2-drpdwn">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-3">
                    <form action="{{route('category.store')}}" method="post">
                        @csrf
                        <div class="card-header">
                            <h5 class="card-title">Add category</h5>
                        </div>
                        <div class="card-body o-hidden">
                            <div class="mb-2">
                                <div class="col-form-label">Category title</div>
                                <input type="text" name="category_name" class="form-control @error('category_name') is-invalid @enderror">
                                @error('category_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <br>
                            <div class="mb-2">
                                <input type="submit" class="btn btn-primary" value="add category">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Update category')
@section('content')
    <div class="select2-drpdwn">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-3">
                    <form action="{{route('category.update',$category)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="card-header">
                            <h5 class="card-title">Update category</h5>
                        </div>
                        <div class="card-body o-hidden">
                            <div class="mb-2">
                                <div class="col-form-label">Category title</div>
                                <input value="{{$category->category_name}}" type="text" name="category_name" class="form-control @error('category_name') is-invalid @enderror">
                                @error('category_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <br>
                            <div class="mb-2">
                                <input type="submit" class="btn btn-primary" value="update category">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/view.blade.php
@extends('admin.layouts.master')
@section('title','View categories')
@section('content')
    <br><br>
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5>All categories</h5>
                <a href="{{route('category.create')}}" class="btn btn-primary">create category</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="display" id="basic-1">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Category title</th>
                            <th>Created date</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $key=>$category)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$category->category_name}}</td>
                                <td>{{$category->created_at}}</td>
                                <td class="d-flex">
                                    <a href="{{route('category.edit',$category)}}" class="btn btn-success">Edit</a>
                                    &nbsp;<form action="{{route('category.destroy', $category)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger show_confirm">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script type="text/javascript">

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Do you want delete category?`,
                // text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>

@endpush