routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('main.index');
//})->name('main.page');

Route::get('/', [\App\Http\Controllers\Main\MainController::class, 'index'])->name('main.page');
Route::get('/category/{id}',[\App\Http\Controllers\Main\MainController::class, 'category_filter'])->name('category.filter');
Route::get('/subcategory/{id}',[\App\Http\Controllers\Main\MainController::class, 'subcategory_filter'])->name('subcategory.filter');
Route::get('/price/{prc}', [\App\Http\Controllers\Main\MainController::class, 'price_filter'])->name('price.filter');
Route::get('/size/{sz}', [\App\Http\Controllers\Main\MainController::class, 'size_filter'])->name('size.filter');
Route::get('/type/{type}', [\App\Http\Controllers\Main\MainController::class, 'type_filter'])->name('type.filter');


Route::middleware(['middleware'=>'back'])->group(function (){
    Auth::routes();
});





//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'dashboard', 'middleware'=>['auth','admin','back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'adminpanel'])->name('adminpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit'])->name('dashboard.setting');
    Route::put('/update/{user}',[\App\Http\Controllers\HomeController::class, 'update'])->name('dashboard.update');
    Route::resource('/role', \App\Http\Controllers\Admin\RoleController::class);
    Route::get('/notifications', [\App\Http\Controllers\User\PetitionController::class, 'notifications'])->name('dashboard.notifications');
    Route::get('/notification/{petition}', [\App\Http\Controllers\User\PetitionController::class, 'notificationshow'])->name('dashboard.notificationshow');
    Route::get('/notification/accept/{petition}',[\App\Http\Controllers\User\PetitionController::class, 'notification_accept'])->name('dashboard.notification_accept');
    Route::post('/notification/cancel/{petition}',[\App\Http\Controllers\User\PetitionController::class, 'notification_cancel'])->name('dashboard.notification_cancel');
    Route::resource('/category', \App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('/subcategory', \App\Http\Controllers\Admin\SubcategoryController::class);
    Route::get('/architectors', [\App\Http\Controllers\Admin\MembersController::class, 'architectors'])->name('dashboard.architectors');
    Route::get('/users', [\App\Http\Controllers\Admin\MembersController::class, 'users'])->name('dashboard.users');
    Route::get('/receive', [\App\Http\Controllers\Architector\ProductController::class, 'recieve'])->name('product.recieve');
    Route::get('/receive/{product}', [\App\Http\Controllers\Architector\ProductController::class, 'show_receive'])->name('product.show_receive');
    Route::post('/product/block', [\App\Http\Controllers\Architector\ProductController::class, 'accept_block'])->name('product.block');
    Route::get('/product/accepts', [\App\Http\Controllers\Architector\ProductController::class, 'accept_models'])->name('product.accept');
    Route::get('/product/cancels', [\App\Http\Controllers\Architector\ProductController::class, 'cancel_models'])->name('product.cancel');
    Route::get('/product/press_accept/{product}', [\App\Http\Controllers\Architector\ProductController::class, 'press_accept'])->name('products.press_accept');
    Route::post('/product/cancel/{product}', [\App\Http\Controllers\Architector\ProductController::class, 'reason'])->name('product.reason');
    Route::post('/spam/architector/{architector}', [\App\Http\Controllers\Architector\SpamController::class, 'architec_spam'])->name('architec.spam');
    Route::get('/nospam/architector/{architector}', [\App\Http\Controllers\Architector\SpamController::class, 'architec_nospam'])->name('architec.nospam');
    Route::post('/spam/user/{user}', [\App\Http\Controllers\Architector\SpamController::class, 'user_spam'])->name('user.spam');
    Route::get('/nospam/user/{user}', [\App\Http\Controllers\Architector\SpamController::class, 'user_nospam'])->name('user.nospam');
    Route::get('/messenger', [\App\Http\Controllers\Admin\AmessengerController::class, 'create'])->name('members.messenger');
    Route::get('/chat/{member}', [\App\Http\Controllers\Admin\AmessengerController::class, 'chat_member'])->name('members.chat');
    Route::post('/messege/text/{account}', [\App\Http\Controllers\Admin\AmessengerController::class, 'admin_message_text'])->name('admin_text_message');
    Route::post('/search', [\App\Http\Controllers\Admin\AmessengerController::class, 'search'])->name('members.search');
    Route::get('/contact', [\App\Http\Controllers\Main\ContactController::class, 'recieve_contact'])->name('recieve.contact');
});

Route::group(['prefix'=>'architector', 'middleware'=>['auth','architector','back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'archtecpanel'])->name('architecpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit_arch'])->name('architec.setting');
    Route::put('/update/{user}', [\App\Http\Controllers\HomeController::class, 'update_arch'])->name('architec.update');
    Route::resource('/product', \App\Http\Controllers\Architector\ProductController::class);
    Route::post('/select/category', [\App\Http\Controllers\Architector\ProductController::class, 'select_category'])->name('architec.category');
    Route::post('/select/subcategory', [\App\Http\Controllers\Architector\ProductController::class,'select_subcategory'])->name('architec.subcategory');
    Route::get('/chat', [\App\Http\Controllers\Admin\AmessengerController::class, 'chat_with_admin'])->name('admin.chat');
    Route::post('/messege/text', [\App\Http\Controllers\Admin\AmessengerController::class, 'architec_text_message'])->name('architec_text_message');
});

Route::group(['prefix'=>'user', 'middleware'=>['auth','user','back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'userpanel'])->name('userpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit_user'])->name('user.setting');
    Route::put('/update/{user}', [\App\Http\Controllers\HomeController::class, 'update_user'])->name('user.update');
    Route::resource('/petition', \App\Http\Controllers\User\PetitionController::class);
    Route::get('/chat', [\App\Http\Controllers\Admin\AmessengerController::class, 'user_chat_with_admin'])->name('user.chat');
    Route::post('/messege/text', [\App\Http\Controllers\Admin\AmessengerController::class, 'user_text_message'])->name('user_text_message');
});

Route::get('/contact', [\App\Http\Controllers\Main\ContactController::class, 'contact_page'])->name('main.contact');
Route::post('/send', [\App\Http\Controllers\Main\ContactController::class, 'store'])->name('contact.store');
Route::get('/product/detail/{product_accept}', [\App\Http\Controllers\Architector\ProductController::class, 'product_detail'])->name('product_detail');

resources/views/admin/partials/navbar.blade.php
<div class="page-header">
    <div class="header-wrapper row m-0">
        <form class="form-inline search-full col" action="#" method="get">
            <div class="form-group w-100">
                <div class="Typeahead Typeahead--twitterUsers">
                    <div class="u-posRelative">
                        <input class="demo-input Typeahead-input form-control-plaintext w-100" type="text" placeholder="Search Cuba .." name="q" title="" autofocus>
                        <div class="spinner-border Typeahead-spinner" role="status"><span class="sr-only">Loading...</span></div><i class="close-search" data-feather="x"></i>
                    </div>
                    <div class="Typeahead-menu"></div>
                </div>
            </div>
        </form>
        <div class="header-logo-wrapper col-auto p-0">
            <div class="logo-wrapper"><a href="index.html"><img class="img-fluid" src="{{asset('admin/assets/images/logo/logo.png')}}" alt=""></a></div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="align-center"></i></div>
        </div>
        <div class="left-header col horizontal-wrapper ps-0">
            <ul class="horizontal-menu">

            </ul>
        </div>
        <div class="nav-right col-8 pull-right right-header p-0">
            <ul class="nav-menus">
                <li class="language-nav">
                    <div class="translate_wrapper">
                        <div class="current_lang">
                            <div class="lang"><i class="flag-icon flag-icon-us"></i><span class="lang-txt">EN                               </span></div>
                        </div>
                        <div class="more_lang">
                            <div class="lang selected" data-value="en"><i class="flag-icon flag-icon-us"></i><span class="lang-txt">English<span> (US)</span></span></div>
                            <div class="lang" data-value="uz"><i class="flag-icon flag-icon-uz"></i><span class="lang-txt">Uzbek</span></div>
                        </div>
                    </div>
                </li>

                <li class="onhover-dropdown">
                    <div class="notification-box"><i data-feather="bell"> </i>
                        <span class="badge rounded-pill badge-secondary">
                            {{$petitions_count}}
                        </span>
                    </div>
                    <ul class="notification-dropdown onhover-show-div">
                        <li><i data-feather="bell"></i>
                            <h6 class="f-14 mb-0">Notitications</h6>
                        </li>
                            @for($i=0; $i<count($petitions); $i++)
                            <li>
                                <a href="{{route('dashboard.notificationshow',$petitions[$i]->id)}}"><i class="fa fa-circle-o me-3 font-primary"> </i>{{$petitions[$i]->user_name->name.' '.$petitions[$i]->user_name->lname}} <span class="pull-right">{{$vaqtlar[$i]}}</span></a>
                            </li>
                            @endfor
                        <li><a class="btn btn-primary" href="{{route('dashboard.notifications')}}">Check all notification</a></li>
                    </ul>
                </li>
                <li>
                    <div class="mode"><i class="fa fa-moon-o"></i></div>
                </li>
                <li class="cart-nav onhover-dropdown">
                    <div class="cart-box"><i data-feather="shopping-cart"></i><span class="badge rounded-pill badge-primary">2</span></div>
                    <ul class="cart-dropdown onhover-show-div">
                        <li>
                            <h6 class="mb-0 f-20">Shoping Bag</h6><i data-feather="shopping-cart"></i>
                        </li>
                        <li class="mt-0">
                            <div class="media"><img class="img-fluid rounded-circle me-3 img-60" src="{{asset('admin/assets/images/ecommerce/01.jpg')}}" alt="">
                                <div class="media-body"><span>V-Neck Shawl Collar Woman's Solid T-Shirt</span>
                                    <p>Yellow(#fcb102)</p>
                                    <div class="qty-box">
                                        <div class="input-group"><span class="input-group-prepend">
                              <button class="btn quantity-left-minus" type="button" data-type="minus" data-field=""><i data-feather="minus"></i></button></span>
                                            <input class="form-control input-number" type="text" name="quantity" value="1"><span class="input-group-prepend">
                              <button class="btn quantity-right-plus" type="button" data-type="plus" data-field=""><i data-feather="plus"></i></button></span>
                                        </div>
                                    </div>
                                    <h6 class="text-end text-muted">$299.00</h6>
                                </div>
                                <div class="close-circle"><a href="#"><i data-feather="x"></i></a></div>
                            </div>
                        </li>
                        <li class="mt-0">
                            <div class="media"><img class="img-fluid rounded-circle me-3 img-60" src="{{asset('admin/assets/images/ecommerce/03.jpg')}}" alt="">
                                <div class="media-body"><span>V-Neck Shawl Collar Woman's Solid T-Shirt</span>
                                    <p>Yellow(#fcb102)</p>
                                    <div class="qty-box">
                                        <div class="input-group"><span class="input-group-prepend">
                              <button class="btn quantity-left-minus" type="button" data-type="minus" data-field=""><i data-feather="minus"></i></button></span>
                                            <input class="form-control input-number" type="text" name="quantity" value="1"><span class="input-group-prepend">
                              <button class="btn quantity-right-plus" type="button" data-type="plus" data-field=""><i data-feather="plus"></i></button></span>
                                        </div>
                                    </div>
                                    <h6 class="text-end text-muted">$299.00</h6>
                                </div>
                                <div class="close-circle"><a href="#"><i data-feather="x"></i></a></div>
                            </div>
                        </li>
                        <li>
                            <div class="total">
                                <h6 class="mb-2 mt-0 text-muted">Order Total : <span class="f-right f-20">$598.00</span></h6>
                            </div>
                        </li>
                        <li><a class="btn btn-block w-100 mb-2 btn-primary view-cart" href="cart.html">Go to shoping bag</a><a class="btn btn-block w-100 btn-secondary view-cart" href="checkout.html">Checkout</a></li>
                    </ul>
                </li>
                <li class="onhover-dropdown"><i data-feather="message-square"></i>
                    <ul class="chat-dropdown onhover-show-div">
                        <li><i data-feather="message-square"></i>
                            <h6 class="f-18 mb-0">Message Box                                    </h6>
                        </li>
                        <li>
                            <div class="media"><img class="img-fluid rounded-circle me-3" src="{{asset('admin/assets/images/user/1.jpg')}}" alt="">
                                <div class="status-circle online"></div>
                                <div class="media-body"><span>Erica Hughes</span>
                                    <p>Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12 font-success">58 mins ago</p>
                            </div>
                        </li>
                        <li>
                            <div class="media"><img class="img-fluid rounded-circle me-3" src="{{asset('admin/assets/images/user/2.jpg')}}" alt="">
                                <div class="status-circle online"></div>
                                <div class="media-body"><span>Kori Thomas</span>
                                    <p>Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12 font-success">1 hr ago</p>
                            </div>
                        </li>
                        <li>
                            <div class="media"><img class="img-fluid rounded-circle me-3" src="{{asset('admin/assets/images/user/4.jpg')}}" alt="">
                                <div class="status-circle offline"></div>
                                <div class="media-body"><span>Ain Chavez</span>
                                    <p>Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12 font-danger">32 mins ago</p>
                            </div>
                        </li>
                        <li class="text-center"> <a class="btn btn-primary" href="{{route('members.messenger')}}">View All     </a></li>
                    </ul>
                </li>
                <li class="maximize"><a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()"><i data-feather="maximize"></i></a></li>
                <li class="profile-nav onhover-dropdown p-0 me-0">
                    <div class="media profile-media"><img class="b-r-10" src="{{asset('admin/assets/images/dashboard/profile.jpg')}}" alt="">
                        <div class="media-body"><span>{{\Illuminate\Support\Facades\Auth::user()->name." ".\Illuminate\Support\Facades\Auth::user()->lname}}</span>
                            <p class="mb-0 font-roboto">Admin <i class="middle fa fa-angle-down"></i></p>
                        </div>
                    </div>
                    <ul class="profile-dropdown onhover-show-div">
                        <li><a href="{{route('dashboard.setting')}}"><i data-feather="settings"></i><span>Settings</span></a></li>
                        <li>
{{--                            <a href="#"><i data-feather="log-in"> </i><span>Log in</span></a>--}}
                            <a class="" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                <i data-feather="log-in"> </i>{{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>

                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <script class="result-template" type="text/x-handlebars-template">
            <div class="ProfileCard u-cf">
            <div class="ProfileCard-avatar"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-airplay m-0"><path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1"></path><polygon points="12 15 17 21 7 21 12 15"></polygon></svg></div>
            <div class="ProfileCard-details">
            <div class="ProfileCard-realName">x</div>
            </div>
            </div>
          </script>
        <script class="empty-template" type="text/x-handlebars-template"><div class="EmptyMessage">Your search turned up 0 results. This most likely means the backend is down, yikes!</div></script>
    </div>
</div>

resources/views/admin/partials/sidebar.blade.php
<div class="sidebar-wrapper">
    <div>
        <div class="logo-wrapper"><a href="index.html"><img class="img-fluid for-light" src="{{asset('admin/assets/images/logo/logo.png')}}" alt=""><img class="img-fluid for-dark" src="{{asset('admin/assets/images/logo/logo_dark.png')}}" alt=""></a>
            <div class="back-btn"><i class="fa fa-angle-left"></i></div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="grid"> </i></div>
        </div>
        <div class="logo-icon-wrapper"><a href="index.html"><img class="img-fluid" src="{{asset('admin/assets/images/logo/logo-icon.png')}}" alt=""></a></div>
        <nav class="sidebar-main">
            <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
            <div id="sidebar-menu">
                <ul class="sidebar-links" id="simple-bar">
                    <li class="back-btn"><a href="index.html"><img class="img-fluid" src="{{asset('admin/assets/images/logo/logo-icon.png')}}" alt=""></a>
                        <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
                    </li>
                    <li class="sidebar-main-title">
                        <div>
                            <h6 class="lan-1">Moduls</h6>
                            <p class="lan-2">Dashboards,widgets & layout.</p>
                        </div>
                    </li>
                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="user-check"></i><span class="">Roles</span></a>
                        <ul class="sidebar-submenu {{(request()->is('dashboard/role/create') ||  request()->is('dashboard/role') ||  request()->is('dashboard/role/*/edit')) ? 'd-block' : ''}}">
                            <li><a class="" href="{{route('role.create')}}" style="color: {{request()->is('dashboard/role/create') ? '#6600FF' : ''}}">Add role</a></li>
                            <li><a class="" href="{{route('role.index')}}" style="color: {{(request()->is('dashboard/role') ||  request()->is('dashboard/role/*/edit')) ? '#6600FF' : ''}}">View roles</a></li>
                        </ul>
                    </li>

                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="layers"></i><span class="">Categories</span></a>
                        <ul class="sidebar-submenu {{(request()->is('dashboard/category/create') ||  request()->is('dashboard/category') ||  request()->is('dashboard/category/*/edit')) ? 'd-block' : ''}}">
                            <li><a class="" href="{{route('category.create')}}" style="color: {{request()->is('dashboard/category/create') ? '#6600FF' : ''}}">Add category</a></li>
                            <li><a class="" href="{{route('category.index')}}" style="color: {{(request()->is('dashboard/category') ||  request()->is('dashboard/category/*/edit')) ? '#6600FF' : ''}}">View categories</a></li>
                        </ul>
                    </li>

                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="list"></i><span class="">Subcategories</span></a>
                        <ul class="sidebar-submenu {{(request()->is('dashboard/subcategory/create') ||  request()->is('dashboard/subcategory') ||  request()->is('dashboard/subcategory/*/edit')) ? 'd-block' : ''}}">
                            <li><a class="" href="{{route('subcategory.create')}}" style="color: {{request()->is('dashboard/subcategory/create') ? '#6600FF' : ''}}">Add subcategory</a></li>
                            <li><a class="" href="{{route('subcategory.index')}}" style="color: {{(request()->is('dashboard/subcategory') ||  request()->is('dashboard/subcategory/*/edit')) ? '#6600FF' : ''}}">View subcategories</a></li>
                        </ul>
                    </li>

                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="users"></i><span class="">Members</span></a>
                        <ul class="sidebar-submenu {{(request()->is('dashboard/architectors') ||  request()->is('dashboard/users')) ? 'd-block' : ''}}">
                            <li><a class="" href="{{route('dashboard.architectors')}}" style="color: {{request()->is('dashboard/architectors') ? '#6600FF' : ''}}">View architectors</a></li>
                            <li><a class="" href="{{route('dashboard.users')}}" style="color: {{(request()->is('dashboard/users') ||  request()->is('dashboard/users/*')) ? '#6600FF' : ''}}">View users</a></li>
                        </ul>
                    </li>

                    <li class="sidebar-list"><label class="badge badge-danger">{{$receive_products_count}}</label>
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="box"></i><span class="">Receivies 3D`</span></a>
                        <ul class="sidebar-submenu {{(request()->routeIs('product.recieve') || request()->routeIs('product.cancel') || request()->routeIs('product.show_receive') || request()->routeIs('product.accept')) ? 'd-block' : ''}}">
                            <li><a class="" href="{{route('product.recieve')}}" style="color: {{(request()->routeIs('product.recieve')) ? '#6600FF' : ''}}">View receiving models</a></li>
                            <li><a class="" href="{{route('product.accept')}}" style="color: {{(request()->routeIs('product.accept')) ? '#6600FF' : ''}}">View accepting model</a></li>
                            <li><a class="" href="{{route('product.cancel')}}" style="color: {{(request()->routeIs('product.cancel')) ? '#6600FF' : ''}}">View canceling model</a></li>
                        </ul>
                    </li>
                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="users"></i><span class="">Messeges from users
                                </span></a>
                        <ul class="sidebar-submenu {{(request()->routeIs('recieve.contact')) ? 'd-block' : ''}}">
                            <li><a class="" href="{{route('recieve.contact')}}" style="color: {{(request()->routeIs('recieve.contact')) ? '#6600FF' : ''}}">View receiving messages</a></li>

                        </ul>
                    </li>
                </ul>
            </div>
            <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
        </nav>
    </div>
</div>